config/routes.rb
Rails.application.routes.draw do
  resources :principles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/principle.rb
class Principle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/principles_controller.rb
class PrinciplesController < ApplicationController
  before_action :set_principle, only: [:show, :edit, :update, :destroy]

  # GET /principles
  # GET /principles.json
  def index
    @principles = Principle.all
  end

  # GET /principles/1
  # GET /principles/1.json
  def show
  end

  # GET /principles/new
  def new
    @principle = Principle.new
  end

  # GET /principles/1/edit
  def edit
  end

  # POST /principles
  # POST /principles.json
  def create
    @principle = Principle.new(principle_params)

    respond_to do |format|
      if @principle.save
        format.html { redirect_to @principle, notice: 'Principle was successfully created.' }
        format.json { render :show, status: :created, location: @principle }
      else
        format.html { render :new }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principles/1
  # PATCH/PUT /principles/1.json
  def update
    respond_to do |format|
      if @principle.update(principle_params)
        format.html { redirect_to @principle, notice: 'Principle was successfully updated.' }
        format.json { render :show, status: :ok, location: @principle }
      else
        format.html { render :edit }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principles/1
  # DELETE /principles/1.json
  def destroy
    @principle.destroy
    respond_to do |format|
      format.html { redirect_to principles_url, notice: 'Principle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principle
      @principle = Principle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principle_params
      params.require(:principle).permit(:life, :money)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principles_helper.rb
module PrinciplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/principles/_form.html.erb
<%= form_for(principle) do |f| %>
  <% if principle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(principle.errors.count, "error") %> prohibited this principle from being saved:</h2>

      <ul>
      <% principle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :life %>
    <%= f.text_field :life %>
  </div>

  <div class="field">
    <%= f.label :money %>
    <%= f.text_area :money %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/principles/edit.html.erb
<h1>Editing Principle</h1>

<%= render 'form', principle: @principle %>

<%= link_to 'Show', @principle %> |
<%= link_to 'Back', principles_path %>

app/views/principles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Principles</h1>

<table>
  <thead>
    <tr>
      <th>Life</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @principles.each do |principle| %>
      <tr>
        <td><%= principle.life %></td>
        <td><%= principle.money %></td>
        <td><%= link_to 'Show', principle %></td>
        <td><%= link_to 'Edit', edit_principle_path(principle) %></td>
        <td><%= link_to 'Destroy', principle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Principle', new_principle_path %>

app/views/principles/new.html.erb
<h1>New Principle</h1>

<%= render 'form', principle: @principle %>

<%= link_to 'Back', principles_path %>

app/views/principles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Life:</strong>
  <%= @principle.life %>
</p>

<p>
  <strong>Money:</strong>
  <%= @principle.money %>
</p>

<%= link_to 'Edit', edit_principle_path(@principle) %> |
<%= link_to 'Back', principles_path %>